"""End-to-end integration test: Resume Parser -> CandidateProfile -> AI Candidate Analysis Layer."""

from unittest.mock import MagicMock

from app.schemas.job import JobProfile
from app.schemas.workflow import CandidateWorkflowRequest
from app.resume import ResumeParser
from app.workflows import CandidateAnalysisWorkflow

# Synthetic resume fixture
SYNTHETIC_RESUME_TEXT = """
Alex Mercer
alex.mercer@example.com | +91 9361465734
linkedin.com/in/alexmercer | github.com/alexmercer

Summary
Software developer with experience building REST APIs in Python and backend services.

Technical Skills
Python, Java, ReactJS, HTML, CSS, NodeJS, ExpressJS, PostgreSQL, Git, GitHub, Postman

Work Experience
Backend Developer Intern at CloudSoft | FEB 2026 - JUL 2026
Built Python REST APIs using FastAPI and PostgreSQL.

Web Developer at School Systems | MAY 2022 - APR 2023
Developed responsive web application features using React and Node.js.

Education
B.E Computer Science Engineering, Tech Institute, 2024

Projects
Birthday Tracker Web Application
AID4ALL Platform

Certifications
AWS Certified Cloud Practitioner
"""

# Fake Job Description as defined in prompt
FAKE_JOB_PROFILE = JobProfile(
    job_title="PYTHON BACKEND DEVELOPER",
    required_skills=["Python", "REST API", "FastAPI", "PostgreSQL", "Git"],
    preferred_skills=["Docker", "Node.js", "Express.js", "MongoDB"],
    experience="1–2 years",
    education=["Computer Science"],
    responsibilities=["Develop scalable backend applications, REST APIs, and cloud-based services."],
)


def test_resume_parser_to_ai_candidate_analysis_workflow_integration() -> None:
    """Verify that CandidateProfile generated by ResumeParser flows directly into AI CandidateAnalysisWorkflow."""
    # Mock LLM provider for predictable test execution without requiring API key
    mock_provider = MagicMock()
    mock_provider.extract.return_value = (
        {
            "name": "Alex Mercer",
            "email": "alex.mercer@example.com",
            "phone": "+919361465734",
            "skills": ["Python", "Java", "React.js", "Node.js", "Express.js", "PostgreSQL", "Git", "GitHub"],
            "work_experience": [
                {
                    "company": "CloudSoft",
                    "role": "Backend Developer Intern",
                    "duration_text": "FEB 2026 - JUL 2026",
                },
                {
                    "company": "School Systems",
                    "role": "Web Developer",
                    "duration_text": "MAY 2022 - APR 2023",
                },
            ],
            "education": [{"degree": "B.E Computer Science Engineering"}],
            "projects": [{"name": "Birthday Tracker Web Application"}, {"name": "AID4ALL Platform"}],
            "certifications": ["AWS Certified Cloud Practitioner"],
        },
        "hybrid",
    )

    parser = ResumeParser(provider=mock_provider)

    # Step 1: Parse raw text into CandidateProfile (pipeline output)
    candidate_profile = parser.parse_text(SYNTHETIC_RESUME_TEXT)

    # Step 2: Verify CandidateProfile structure
    assert candidate_profile.name == "Alex Mercer"
    assert candidate_profile.email == "alex.mercer@example.com"
    assert "Python" in candidate_profile.skills
    assert "Node.js" in candidate_profile.skills
    assert isinstance(candidate_profile.experience, str)
    assert len(candidate_profile.experience_entries) >= 1

    # Step 3: Pass CandidateProfile directly into AI Candidate Analysis Layer
    workflow = CandidateAnalysisWorkflow()
    workflow_request = CandidateWorkflowRequest(
        job_profile=FAKE_JOB_PROFILE,
        candidate_profile=candidate_profile,
    )
    result = workflow.run(workflow_request)

    # Step 4: Verify AI Core outputs
    assert result.match.overall_match_score > 0
    assert "Python" in result.match.matched_skills
    assert result.evaluation.summary is not None
    assert result.skill_gap is not None
    assert result.recommendations is not None
