import React, { useEffect, useState } from "react";
import { Sparkles, BookOpen, CheckCircle2, Code2, ArrowRight } from "lucide-react";
import { API_URL, LearningRecommendation, StoredApplication } from "../../api";
import { useAuth } from "../../auth/AuthContext";
import { Card } from "../ui/Card";
import { Badge } from "../ui/Badge";
import { EmptyState } from "../ui/EmptyState";
import { LoadingState } from "../ui/LoadingState";
import { PageHeader } from "../ui/PageHeader";

export const CandidateRecommendations: React.FC = () => {
  const { token } = useAuth();
  const [applications, setApplications] = useState<StoredApplication[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (!token) return;
    setIsLoading(true);
    fetch(`${API_URL}/applications`, {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then((res) => (res.ok ? res.json() : []))
      .then(setApplications)
      .catch(console.error)
      .finally(() => setIsLoading(false));
  }, [token]);

  if (isLoading) {
    return <LoadingState message="Synthesizing personalized learning roadmaps..." rows={4} />;
  }

  // Aggregate all unique recommendations across applications
  const recMap = new Map<string, LearningRecommendation>();
  applications.forEach((app) => {
    app.recommendations?.recommendations?.forEach((rec) => {
      if (!recMap.has(rec.skill)) {
        recMap.set(rec.skill, rec);
      }
    });
  });

  const recommendationList = Array.from(recMap.values());

  if (recommendationList.length === 0) {
    return (
      <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
        <PageHeader
          title="Personalized Skill Recommendations"
          subtitle="Curated, step-by-step upskilling roadmaps generated by AI recommendations."
        />
        <EmptyState
          title="No Upskilling Roadmaps Yet"
          description="Submit an application to a job to generate custom milestone paths tailored to your detected skill gaps."
        />
      </div>
    );
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
      <PageHeader
        title="Personalized Skill Recommendations"
        subtitle="Step-by-step milestone learning sequences and practical projects generated to close skill gaps."
      />

      <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
        {recommendationList.map((rec, rIdx) => {
          const isHigh = (rec.priority || "").toLowerCase() === "high" || (rec.priority || "").toLowerCase() === "critical";

          return (
            <Card key={rIdx} elevated>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: "12px", marginBottom: "12px" }}>
                <div>
                  <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                    <h3 style={{ fontSize: "18px", fontWeight: 700, color: "var(--text-primary)", margin: 0 }}>
                      {rec.skill}
                    </h3>
                    <Badge variant={isHigh ? "danger" : "warning"} size="sm">
                      {rec.priority.toUpperCase()} PRIORITY
                    </Badge>
                  </div>
                  <p style={{ fontSize: "14px", color: "var(--text-secondary)", marginTop: "6px", lineHeight: 1.5 }}>
                    <strong style={{ color: "var(--text-primary)" }}>Why: </strong>
                    {rec.reason}
                  </p>
                </div>
              </div>

              {/* Milestone Sequence */}
              <div style={{ marginTop: "16px", paddingTop: "16px", borderTop: "1px solid var(--border-subtle)" }}>
                <span style={{ fontSize: "12px", fontWeight: 600, color: "var(--accent-primary)", textTransform: "uppercase", letterSpacing: "0.05em", display: "block", marginBottom: "12px" }}>
                  Step-by-Step Learning Path
                </span>

                <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
                  {rec.learning_path?.map((step, sIdx) => (
                    <div
                      key={sIdx}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "12px",
                        padding: "10px 14px",
                        backgroundColor: "var(--bg-input)",
                        border: "1px solid var(--border-subtle)",
                        borderRadius: "var(--radius-md)",
                      }}
                    >
                      <span
                        style={{
                          width: "24px",
                          height: "24px",
                          borderRadius: "50%",
                          backgroundColor: "rgba(99, 102, 241, 0.2)",
                          color: "#818CF8",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          fontSize: "12px",
                          fontWeight: 700,
                          flexShrink: 0,
                        }}
                      >
                        {sIdx + 1}
                      </span>
                      <span style={{ fontSize: "13px", color: "var(--text-primary)", fontWeight: 500 }}>
                        {step}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Practical Project Suggestion */}
              <div
                style={{
                  marginTop: "16px",
                  padding: "12px 16px",
                  backgroundColor: "rgba(124, 58, 237, 0.08)",
                  border: "1px solid rgba(124, 58, 237, 0.2)",
                  borderRadius: "var(--radius-md)",
                  display: "flex",
                  alignItems: "center",
                  gap: "10px",
                }}
              >
                <Code2 size={18} color="var(--accent-secondary)" />
                <span style={{ fontSize: "13px", color: "var(--text-primary)" }}>
                  <strong>Practical Project Suggestion:</strong> Build a hands-on project utilizing <strong>{rec.skill}</strong> and link it to your GitHub portfolio to boost your next ATS match score.
                </span>
              </div>
            </Card>
          );
        })}
      </div>
    </div>
  );
};
